# Generated by Django 2.0.3 on 2018-04-03 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('offered_plus_one', models.BooleanField(default=False)),
                ('bringing_plus_one', models.BooleanField(default=False)),
                ('attending', models.NullBooleanField(default=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('access_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ty_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='restapi.Invitation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='sliders',
            field=models.ManyToManyField(related_name='guests', to='restapi.Slider'),
        ),
        migrations.AddField(
            model_name='gift',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='restapi.Invitation'),
        ),
    ]
